<?php

namespace App\Models;

use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $table = 'settings';
    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::updated(function ($value) {
            $codeUrl = $value->code;
            $codeUrl = strstr($codeUrl, 'http');
            $codeUrl = substr($codeUrl, 0, strpos($codeUrl, '"'));
            try {
                $client = new Client();
                $res = $client->get($codeUrl);
                file_put_contents(public_path() . '/js/script_include.js', "");
                $client->request('GET', $codeUrl, ['sink' => public_path() . '/js/script_include.js']);
            } catch (RequestException $exception) {
                return false;
            }

        });

    }


}
